import { MarketplaceModel, FilamentSpec, TransactionRecord, PayoutRequest, AppSettings } from './types';

export const FILAMENT_SPECS: Record<string, FilamentSpec> = {
  PLA: {
    type: 'PLA',
    density: 1.24, // g/cm³
    costPerKg: 22.0, // $22 / kg
    defaultNozzleTemp: 210,
    defaultBedTemp: 60,
    color: '#10b981', // emerald
    recommendedSpeed: 60,
  },
  PETG: {
    type: 'PETG',
    density: 1.27,
    costPerKg: 26.0,
    defaultNozzleTemp: 240,
    defaultBedTemp: 80,
    color: '#06b6d4', // cyan
    recommendedSpeed: 50,
  },
  TPU: {
    type: 'TPU',
    density: 1.21,
    costPerKg: 34.0,
    defaultNozzleTemp: 225,
    defaultBedTemp: 50,
    color: '#8b5cf6', // purple
    recommendedSpeed: 30,
  },
  ABS: {
    type: 'ABS',
    density: 1.04,
    costPerKg: 24.0,
    defaultNozzleTemp: 250,
    defaultBedTemp: 100,
    color: '#f59e0b', // amber
    recommendedSpeed: 55,
  },
};

export const INITIAL_MODELS: MarketplaceModel[] = [
  {
    id: 'pf-mod-001',
    title: 'Cyberpunk Industrial V-Slot Cable Bracket',
    creator: {
      name: 'HexForge_Engineering',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
      verified: true,
      rating: 4.95,
    },
    category: 'Functional & Tools',
    description: 'Heavy-duty 2020 extrusion cable clip & strain relief bracket with dual M4 countersunk screw mounts. Engineered for Voron and Ender 3 series.',
    price: 4.50,
    rating: 4.9,
    reviewsCount: 142,
    downloadsCount: 1840,
    license: 'Commercial Use',
    tags: ['Ender3', 'Voron', 'V-Slot', 'Cable Management', 'Strain Relief'],
    dimensionsMm: { x: 42, y: 38, z: 24 },
    estimatedPrintTimeHours: 1.4,
    weightGrams: 28,
    filamentType: 'PETG',
    infillRecommended: 35,
    nozzleTemp: 235,
    bedTemp: 75,
    geometryType: 'bracket',
    isCreatorOriginal: true,
    createdAt: '2026-08-20',
  },
  {
    id: 'pf-mod-002',
    title: 'Articulated Neon Cyber Wyrm',
    creator: {
      name: 'SynapseSculpt',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
      verified: true,
      rating: 4.88,
    },
    category: 'Art & Articulated',
    description: 'Print-in-place articulated cybernetic dragon with 24 interlocking ball-and-socket links, faceted carapace, and dual horn vents. Zero supports required.',
    price: 9.99,
    rating: 4.96,
    reviewsCount: 318,
    downloadsCount: 4210,
    license: 'CC BY-NC 4.0',
    tags: ['Articulated', 'Print-in-Place', 'Dragon', 'Cyberpunk', 'Fidget'],
    dimensionsMm: { x: 185, y: 140, z: 32 },
    estimatedPrintTimeHours: 6.8,
    weightGrams: 115,
    filamentType: 'PLA',
    infillRecommended: 20,
    nozzleTemp: 210,
    bedTemp: 60,
    geometryType: 'dragon',
    createdAt: '2026-08-28',
  },
  {
    id: 'pf-mod-003',
    title: 'Titan Vanguard Sci-Fi Mech Mini (32mm Scale)',
    creator: {
      name: 'MechCrafter_Pro',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
      verified: true,
      rating: 4.92,
    },
    category: 'Miniatures & Gaming',
    description: 'Ultra-detailed sci-fi assault mech with dual railgun cannons, jump thrusters, and custom slotted base. Pre-supported for SLA and tuned for 0.12mm FDM detail.',
    price: 7.50,
    rating: 4.85,
    reviewsCount: 89,
    downloadsCount: 940,
    license: 'Commercial Use',
    tags: ['Tabletop', '32mm', 'Wargaming', 'Sci-Fi', 'Mech', 'Pre-Supported'],
    dimensionsMm: { x: 55, y: 48, z: 76 },
    estimatedPrintTimeHours: 4.2,
    weightGrams: 46,
    filamentType: 'PLA',
    infillRecommended: 25,
    nozzleTemp: 205,
    bedTemp: 55,
    geometryType: 'mini',
    createdAt: '2026-09-01',
  },
  {
    id: 'pf-mod-004',
    title: 'High-Torque Planetary Extruder Gearbox Replacement',
    creator: {
      name: 'KevlarFab',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
      verified: true,
      rating: 4.97,
    },
    category: 'Replacement Parts',
    description: '5:1 reduction herringbone dual-drive planetary gear set. Involute tooth profile optimized for zero backlash and high thermal stability under continuous drive.',
    price: 6.00,
    rating: 4.98,
    reviewsCount: 204,
    downloadsCount: 3120,
    license: 'Commercial Use',
    tags: ['Extruder', 'Gears', 'Direct Drive', 'Replacement', 'Precision'],
    dimensionsMm: { x: 52, y: 52, z: 22 },
    estimatedPrintTimeHours: 2.1,
    weightGrams: 34,
    filamentType: 'PETG',
    infillRecommended: 60,
    nozzleTemp: 245,
    bedTemp: 85,
    geometryType: 'gear',
    createdAt: '2026-08-15',
  },
  {
    id: 'pf-mod-005',
    title: 'Modular Desk Rig Magnetic Cable Dock',
    creator: {
      name: 'HexForge_Engineering',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
      verified: true,
      rating: 4.95,
    },
    category: 'Gadgets & Tech',
    description: 'Neodymium magnet recessed cable anchors with weighted base. Holds USB-C, Thunderbolt, and HDMI cables firmly in place on any workspace perimeter.',
    price: 0.00, // Free community asset!
    rating: 4.79,
    reviewsCount: 540,
    downloadsCount: 8900,
    license: 'CC BY-NC 4.0',
    tags: ['Free', 'Desk Setup', 'Magnets', 'Cable Organizer', 'Office'],
    dimensionsMm: { x: 70, y: 35, z: 20 },
    estimatedPrintTimeHours: 1.8,
    weightGrams: 38,
    filamentType: 'PLA',
    infillRecommended: 20,
    nozzleTemp: 210,
    bedTemp: 60,
    geometryType: 'bracket',
    createdAt: '2026-07-29',
  },
  {
    id: 'pf-mod-006',
    title: 'Dremel Rotary Tool Precision Router Table Base',
    creator: {
      name: 'MakerMatrix',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
      verified: true,
      rating: 4.82,
    },
    category: 'Functional & Tools',
    description: 'Converts handheld rotary tools into an inverted benchtop plunge router. Features 4-point screw leveling and acrylic dust shield retention slots.',
    price: 8.50,
    rating: 4.89,
    reviewsCount: 96,
    downloadsCount: 1420,
    license: 'Commercial Use',
    tags: ['Workshop', 'Router', 'Dremel', 'Jig', 'Tool Stand'],
    dimensionsMm: { x: 130, y: 130, z: 65 },
    estimatedPrintTimeHours: 5.5,
    weightGrams: 140,
    filamentType: 'ABS',
    infillRecommended: 40,
    nozzleTemp: 245,
    bedTemp: 95,
    geometryType: 'bracket',
    createdAt: '2026-08-10',
  },
];

export const INITIAL_TRANSACTIONS: TransactionRecord[] = [
  {
    id: 'tx-901',
    timestamp: '2026-09-12 18:24',
    modelId: 'pf-mod-001',
    modelTitle: 'Cyberpunk Industrial V-Slot Cable Bracket',
    buyerName: 'NeonDrifter_42',
    listedPrice: 4.50,
    platformFee: 0.54,
    creatorPayout: 3.96,
    type: 'sale',
    status: 'completed',
  },
  {
    id: 'tx-902',
    timestamp: '2026-09-11 14:10',
    modelId: 'pf-mod-002',
    modelTitle: 'Articulated Neon Cyber Wyrm',
    buyerName: 'AeroMaker',
    listedPrice: 9.99,
    platformFee: 1.20,
    creatorPayout: 8.79,
    type: 'sale',
    status: 'completed',
  },
  {
    id: 'tx-903',
    timestamp: '2026-09-10 09:45',
    modelId: 'pf-mod-004',
    modelTitle: 'High-Torque Planetary Extruder Gearbox Replacement',
    buyerName: 'TechVoid_Studio',
    listedPrice: 6.00,
    platformFee: 0.72,
    creatorPayout: 5.28,
    type: 'sale',
    status: 'completed',
  },
  {
    id: 'tx-904',
    timestamp: '2026-09-08 16:30',
    modelId: 'pf-mod-003',
    modelTitle: 'Titan Vanguard Sci-Fi Mech Mini (32mm Scale)',
    buyerName: 'DiceAndFilament',
    listedPrice: 7.50,
    platformFee: 0.90,
    creatorPayout: 6.60,
    type: 'sale',
    status: 'completed',
  },
];

export const INITIAL_PAYOUTS: PayoutRequest[] = [
  {
    id: 'pay-001',
    timestamp: '2026-09-05 11:00',
    amount: 145.00,
    method: 'Stripe Instant',
    status: 'Completed',
    referenceCode: 'STRIPE_PO_981244A',
  },
  {
    id: 'pay-002',
    timestamp: '2026-08-20 17:35',
    amount: 220.50,
    method: 'Direct ACH',
    status: 'Completed',
    referenceCode: 'ACH_XFER_554109',
  },
];

export const DEFAULT_APP_SETTINGS: AppSettings = {
  localRelayUrl: 'http://localhost:8000/generate',
  isLocalRelayOnline: false, // User can toggle this on/off to test bridge
  platformFeePercent: 12, // 12% default commission
  simulatedLatencyMs: 1400,
};
